const lang = {
  ht: {
    dashboard: 'Tableau de Bord',
    clients: 'Jesyon Kliyan',
    transactions: 'Tranzaksyon',
    loans: 'Jesyon Pre',
    reports: 'Rapo',
    team: 'Ekip',
    logout: 'Dekonekte',
    welcome: 'Byenveni',
    newClient: 'Nouvo Kliyan',
    search: 'Chèche',
    save: 'Sove',
    cancel: 'Anile',
    deposit: 'Depo',
    withdraw: 'Retre',
    transfer: 'Transfe',
    language: 'Lang',
  },
  fr: {
    dashboard: 'Tableau de Bord',
    clients: 'Gestion Clients',
    transactions: 'Transactions',
    loans: 'Gestion Prêts',
    reports: 'Rapports',
    team: 'Équipe',
    logout: 'Déconnexion',
    welcome: 'Bienvenue',
    newClient: 'Nouveau Client',
    search: 'Rechercher',
    save: 'Enregistrer',
    cancel: 'Annuler',
    deposit: 'Dépôt',
    withdraw: 'Retrait',
    transfer: 'Transfert',
    language: 'Langue',
  },
  en: {
    dashboard: 'Dashboard',
    clients: 'Client Management',
    transactions: 'Transactions',
    loans: 'Loan Management',
    reports: 'Reports',
    team: 'Team',
    logout: 'Logout',
    welcome: 'Welcome',
    newClient: 'New Client',
    search: 'Search',
    save: 'Save',
    cancel: 'Cancel',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    transfer: 'Transfer',
    language: 'Language',
  },
  es: {
    dashboard: 'Panel Principal',
    clients: 'Gestión Clientes',
    transactions: 'Transacciones',
    loans: 'Gestión Préstamos',
    reports: 'Informes',
    team: 'Equipo',
    logout: 'Cerrar Sesión',
    welcome: 'Bienvenido',
    newClient: 'Nuevo Cliente',
    search: 'Buscar',
    save: 'Guardar',
    cancel: 'Cancelar',
    deposit: 'Depósito',
    withdraw: 'Retiro',
    transfer: 'Transferencia',
    language: 'Idioma',
  },
  pt: {
    dashboard: 'Painel Principal',
    clients: 'Gestão Clientes',
    transactions: 'Transações',
    loans: 'Gestão Empréstimos',
    reports: 'Relatórios',
    team: 'Equipe',
    logout: 'Sair',
    welcome: 'Bem-vindo',
    newClient: 'Novo Cliente',
    search: 'Pesquisar',
    save: 'Salvar',
    cancel: 'Cancelar',
    deposit: 'Depósito',
    withdraw: 'Saque',
    transfer: 'Transferência',
    language: 'Idioma',
  },
};

export default lang;